builders:
  abi_generator:
    build_extensions: 
      ".abi.json": [".g.dart"]
    import: "package:dart_web3/src/builder/builders.dart"
    builder_factories: ["abiGenerator"]
    build_to: source
    auto_apply: dependents
    applies_builders: [ ':delete_abi_source' ]

post_process_builders:
  delete_abi_source:
    import: "package:dart_web3/src/builder/builders.dart"
    input_extensions: [".abi.json"]
    builder_factory: "deleteSource"
    defaults:
      release_options:
        enabled: true
